# Generated by Django 2.1.7 on 2019-02-15 19:52

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190215_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=django.utils.datetime_safe.datetime.now, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='notification',
            field=models.TextField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='toi',
            field=models.CharField(choices=[('team', 'Team Event'), ('single', 'Individual Event')], default=django.utils.datetime_safe.datetime.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='branch',
            field=models.CharField(choices=[('civil', 'Civil'), ('mech', 'Mechanical'), ('ece', 'ECE'), ('cs', 'CS'), ('it', 'IT'), ('ee', 'EE')], default=django.utils.datetime_safe.datetime.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='roll_no',
            field=models.CharField(default=django.utils.datetime_safe.datetime.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default=django.utils.datetime_safe.datetime.now, max_length=128),
            preserve_default=False,
        ),
    ]
