# Generated by Django 2.1.7 on 2019-02-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190215_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='notification',
        ),
        migrations.AlterField(
            model_name='participant',
            name='branch',
            field=models.CharField(choices=[('civil', 'Civil'), ('mech', 'Mechanical'), ('ece', 'ECE'), ('cs', 'CS'), ('it', 'IT'), ('ee', 'EE'), ('others', 'Others')], max_length=128),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
    ]
