# Generated by Django 2.1.7 on 2019-02-15 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190215_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.TextField(default=datetime.datetime(2019, 2, 15, 21, 15, 13, 764246)),
            preserve_default=False,
        ),
    ]
