# Generated by Django 2.1.7 on 2019-02-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='branch',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('ECE', 'ECE'), ('CS', 'CS'), ('IT', 'IT'), ('EE', 'EE'), ('Others', 'Others')], default='IT', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='mobile_number',
            field=models.CharField(default='876545679', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='3', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='branch',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('ECE', 'ECE'), ('CS', 'CS'), ('IT', 'IT'), ('EE', 'EE'), ('Others', 'Others')], max_length=128),
        ),
    ]
