# Generated by Django 2.1.7 on 2019-02-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190216_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
