# Generated by Django 2.1.7 on 2019-02-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_team_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('participation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ParticipatedEvent')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Participant')),
            ],
        ),
    ]
